apiPackages:
  node:
    routes:
      - name: /statistics
        open: true
        secured: false
        rateLimit: 10
      - name: /peerinfo
        open: true
        secured: false
        rateLimit: 10
      - name: /overview
        open: true
        secured: false
        rateLimit: 10
      - name: /locations
        open: true
        secured: false
        rateLimit: 15
      - name: /aggregate
        open: true
        secured: false
        rateLimit: 15
  address:
    routes:
      - name: "/:address"
        open: true
        secured: false
        rateLimit: 30
      - name: "/:address/overview"
        open: true
        secured: false
        rateLimit: 30
      - name: "/:address/collection/:collectionID"
        open: true
        secured: false
        rateLimit: 30
      - name: "/:address/balance"
        open: true
        secured: false
        rateLimit: 30
      - name: "/:address/nonce"
        open: true
        secured: false
        rateLimit: 30
      - name: "/:address/allowance"
        open: true
        secured: false
        rateLimit: 30
      - name: "/:address/allowance/list"
        open: true
        secured: false
        rateLimit: 20
      - name: "/:address/username"
        open: true
        secured: false
        rateLimit: 30
      - name: "/:address/keys"
        open: true
        secured: false
        rateLimit: 10
      - name: "/list"
        open: true
        secured: false
        rateLimit: 10
      - name: "/topsenders"
        open: true
        secured: false
        rateLimit: 10
      - name: "/:address/transactions"
        open: true
        secured: false
        rateLimit: 30
      - name: "/list/count/:rangeOfLastDays"
        open: true
        secured: false
        rateLimit: 30
      - name: "/list/histogram/:rangeOfLastDays"
        open: true
        secured: false
        rateLimit: 30
      - name: "/lastclaim"
        open: true
        secured: false
        rateLimit: 30
      - name: "/statistics"
        open: true
        secured: false
        rateLimit: 30
  assets:
    routes:
      - name: "/:id"
        open: true
        secured: false
        rateLimit: 60
      - name: "/:id/:nonce"
        open: true
        secured: false
        rateLimit: 60
      - name: "/list"
        open: true
        secured: false
        rateLimit: 10
      - name: "/sft/:id"
        open: true
        secured: false
        rateLimit: 0
      - name: "/sft/:id/:nonce"
        open: true
        secured: false
        rateLimit: 0
      # deprecated
      - name: "/kassets"
        open: true
        secured: false
        rateLimit: 10
      - name: "/holders/:assetID"
        open: true
        secured: false
        rateLimit: 30
      - name: "/nft/holder/*nftID"
        open: true
        secured: false
        rateLimit: 30
      - name: "/pool/list"
        open: true
        secured: false
        rateLimit: 10
      - name: "/pool/:poolID"
        open: true
        secured: false
        rateLimit: 30
      - name: "/precisions"
        open: true
        secured: false
        rateLimit: 30
  proposals:
    routes:
      - name: "/:id"
        open: true
        secured: false
        rateLimit: 60
      - name: "/list"
        open: true
        secured: false
        rateLimit: 30
  marketplaces:
    routes:
      - name: "/:id"
        open: true
        secured: false
        rateLimit: 60
      - name: "/:id/orders"
        open: true
        secured: false
        rateLimit: 30
      - name: "/:id/collections"
        open: true
        secured: false
        rateLimit: 60
      - name: "/:id/collections/*asset"
        open: true
        secured: false
        rateLimit: 30
      - name: "/list"
        open: true
        secured: false
        rateLimit: 10
      - name: "/:id/leaderboard"
        open: true
        secured: false
        rateLimit: 30
      - name: "/nfts/activity"
        open: true
        secured: false
        rateLimit: 30
      - name: "/:id/:collection/:nftID"
        open: true
        secured: false
        rateLimit: 30
  block:
    routes:
      - name: "/by-hash/:hash"
        open: true
        secured: false
        rateLimit: 60
      - name: "/by-nonce/:nonce"
        open: true
        secured: false
        rateLimit: 60
      - name: "/list"
        open: true
        secured: false
        rateLimit: 30
      - name: "/statistics-by-day/:rangeOfLastDays"
        open: true
        secured: false
        rateLimit: 30
      - name: "/statistics-total/:rangeOfLastDays"
        open: true
        secured: false
        rateLimit: 30
  network:
    routes:
      - name: /economics
        open: true
        secured: false
        rateLimit: 30
      - name: /config
        open: true
        secured: false
        rateLimit: 30
      - name: /direct-staked-info
        open: true
        secured: true
        rateLimit: 30
      - name: /delegated-info
        open: true
        secured: true
        rateLimit: 30
      - name: /enable-epochs
        open: true
        secured: false
        rateLimit: 30
      - name: /network-parameters
        open: true
        secured: false
        rateLimit: 30
  validator:
    routes:
      - name: /list
        open: true
        secured: false
        rateLimit: 30
      - name: /:address
        open: true
        secured: false
        rateLimit: 30
      - name: /delegated/list
        open: true
        secured: false
        rateLimit: 30
      - name: /delegated/:address
        open: true
        secured: false
        rateLimit: 30
      - name: /best-matches
        open: true
        secured: false
        rateLimit: 30
      - name: /blocks/:bls
        open: true
        secured: false
        rateLimit: 10
      - name: /statistics
        open: true
        secured: false
        rateLimit: 30
  epoch:
    routes:
      - name: /:id
        open: true
        secured: false
        rateLimit: 30
      - name: /list
        open: true
        secured: false
        rateLimit: 30
  transaction:
    routes:
      - name: /decode
        open: true
        secured: false
        rateLimit: 30
      - name: /send
        open: true
        secured: false
        rateLimit: 30
      - name: /simulate
        open: true
        secured: false
        rateLimit: 30
      - name: /send-multiple
        open: true
        secured: false
        rateLimit: 30
      - name: /send-user-funds/:address
        open: false
        secured: false
        rateLimit: 2
      - name: /send-user-funds/:address/status
        open: false
        secured: false
        rateLimit: 120
      - name: /cost
        open: true
        secured: false
        rateLimit: 30
      - name: "/:txhash"
        open: true
        secured: false
        rateLimit: 60
      - name: "/by-type/:type"
        open: true
        secured: false
        rateLimit: 30
      - name: "/:txhash/status"
        open: true
        secured: false
        rateLimit: 30
      - name: "/list"
        open: true
        secured: false
        rateLimit: 15
      - name: "/list/count/:rangeOfLastDays"
        open: true
        secured: false
        rateLimit: 15
      - name: "/list/histogram/:rangeOfLastDays"
        open: true
        secured: false
        rateLimit: 15
      - name: "/count/bymonth"
        open: true
        secured: false
        rateLimit: 15
      - name: "/statistics"
        open: true
        secured: false
        rateLimit: 20
  ito:
    routes:
      - name: '/:id'
        open: true
        secured: false
        rateLimit: 15
      - name: "/list"
        open: true
        secured: false
        rateLimit: 10
  sc:
    routes:
      - name: "/:address"
        secured: false
        open: true
        rateLimit: 30
      - name: "/list"
        open: true
        secured: false
        rateLimit: 30
  proof:
    routes:
      - name: "/root-hash/:roothash/address/:address"
        secured: false
        open: false
        rateLimit: 10
      - name: "/address/:address"
        secured: false
        open: false
        rateLimit: 10
      - name: /verify
        secured: false
        open: false
        rateLimit: 10
  health:
    routes:
      - name: "/health"
        secured: false
        open: true
        rateLimit: 20
